### ISSUE TITLE
Double Posts

### ISSUE THREAD

**Issue by theotherzach** [b0xw00d/twitter_code_challenge#1]
Repro: always
Observed on Safari 9.

1. Enter text into the status field.
2. Hit enter twice in rapid succession
 - **Result:** Double post
 - **Expected:** Single post

**Comment by theotherzach** [comment]
Bonus points for writing a failing test before fixing the issue.

**Comment by b0xw00d** [comment]
Simple fix.

**I changed this:**
```javascript
      success: function(result){
        $(result).hide().prependTo(allPosts).fadeIn(1000);
        $("#post_content").val("");
```

**to this:**
```javascript
      success: function(result){
        $(result).hide().prependTo(allPosts).fadeIn(1000);
        $("#post_content").val("").blur();
```

**Comment by b0xw00d** [comment]
never mind. doesn't fix in safari.

**Comment by b0xw00d** [comment]
Fixed it!  :-D
