### ISSUE TITLE
[Feature Request] Animation

### ISSUE THREAD

**Issue by theotherzach** [b0xw00d/twitter_code_challenge#3]
Would you mind adding some animation to your UI? An example might be having newly posted posts start small & grow in height, pushing the previous posts down.

**Comment by b0xw00d** [comment]
I currently have new posts being prepended with a fade in at 1000ms.  It's silky smooth on my local machine but lagging on heroku at times.  Is this what you mean or were you referring to something more substantial?  Also, is there a better/more conventional way to do this?  Thanks, again!  Code snippet below.

```javascript
      success: function(result){
        $(result).hide().prependTo(allPosts).fadeIn(1000);
```

**Comment by theotherzach** [comment]
I'd look into CSS animations, but the effect works well.

**Comment by theotherzach** [comment]
(Also, looks good.)
